name: Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["**"]
    tags-ignore: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: ["1.13.4", "1.14.5", "1.15.7"]
        otp: ["24.3.4.14", "25.3.2.7", "26.1.2"]

    services:
      db:
        image: postgres:12-alpine
        ports: ["54323:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          MIX_ENV=test mix deps.compile
          mix dialyzer --plt

      - name: Audit dependencies
        run: mix hex.audit

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Check Unused deps
        run: mix deps.unlock --check-unused

      - name: Compile project without warnings
        run: |
          mix compile --warnings-as-errors
          MIX_ENV=test mix compile --warnings-as-errors

      - name: Run Credo
        run: mix credo --strict

      - name: Run Dialyzer
        run: mix dialyzer --no-check

      - name: Run tests
        run: mix test
